services:
  db:
    image: mysql:8.4
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "8820:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - weblab820
    # แนะนำเพิ่ม restart policy เพื่อให้ DB รันขึ้นมาใหม่ถ้าเครื่องดับ
    restart: always 

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"  
    depends_on:
      - db
    networks:
      - weblab820
    restart: always

networks:
  weblab820:
    driver: bridge

volumes:
  mysql_data:
    driver: local